apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-phpbb
 namespace: forum
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: phpbb
 minReplicas: 5
 maxReplicas: 15
 targetCPUUtilizationPercentage: 50
