apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: {{ .Release.Name }}-mariadb
